import type { Locale } from "@/lib/i18n";

/** ITU-T E.164 calling codes, one row per ISO 3166-1 territory. Used to build
 * the phone field's country selector (ContactFields, B2BEnquiryForm) — the
 * number input stays a national-format value, this supplies the prefix. */
export type CountryCode = {
  iso2: string;
  dialCode: string;
  fr: string;
  en: string;
};

export const DEFAULT_COUNTRY_ISO2 = "FR";

export const COUNTRY_CODES: CountryCode[] = [
  { iso2: "AF", dialCode: "+93", fr: "Afghanistan", en: "Afghanistan" },
  { iso2: "ZA", dialCode: "+27", fr: "Afrique du Sud", en: "South Africa" },
  { iso2: "AL", dialCode: "+355", fr: "Albanie", en: "Albania" },
  { iso2: "DZ", dialCode: "+213", fr: "Algérie", en: "Algeria" },
  { iso2: "DE", dialCode: "+49", fr: "Allemagne", en: "Germany" },
  { iso2: "AD", dialCode: "+376", fr: "Andorre", en: "Andorra" },
  { iso2: "AO", dialCode: "+244", fr: "Angola", en: "Angola" },
  { iso2: "AI", dialCode: "+1264", fr: "Anguilla", en: "Anguilla" },
  {
    iso2: "AG",
    dialCode: "+1268",
    fr: "Antigua-et-Barbuda",
    en: "Antigua and Barbuda",
  },
  {
    iso2: "SA",
    dialCode: "+966",
    fr: "Arabie saoudite",
    en: "Saudi Arabia",
  },
  { iso2: "AR", dialCode: "+54", fr: "Argentine", en: "Argentina" },
  { iso2: "AM", dialCode: "+374", fr: "Arménie", en: "Armenia" },
  { iso2: "AW", dialCode: "+297", fr: "Aruba", en: "Aruba" },
  { iso2: "AU", dialCode: "+61", fr: "Australie", en: "Australia" },
  { iso2: "AT", dialCode: "+43", fr: "Autriche", en: "Austria" },
  { iso2: "AZ", dialCode: "+994", fr: "Azerbaïdjan", en: "Azerbaijan" },
  { iso2: "BS", dialCode: "+1242", fr: "Bahamas", en: "Bahamas" },
  { iso2: "BH", dialCode: "+973", fr: "Bahreïn", en: "Bahrain" },
  { iso2: "BD", dialCode: "+880", fr: "Bangladesh", en: "Bangladesh" },
  { iso2: "BB", dialCode: "+1246", fr: "Barbade", en: "Barbados" },
  { iso2: "BE", dialCode: "+32", fr: "Belgique", en: "Belgium" },
  { iso2: "BZ", dialCode: "+501", fr: "Belize", en: "Belize" },
  { iso2: "BJ", dialCode: "+229", fr: "Bénin", en: "Benin" },
  { iso2: "BM", dialCode: "+1441", fr: "Bermudes", en: "Bermuda" },
  { iso2: "BT", dialCode: "+975", fr: "Bhoutan", en: "Bhutan" },
  { iso2: "BY", dialCode: "+375", fr: "Biélorussie", en: "Belarus" },
  { iso2: "MM", dialCode: "+95", fr: "Birmanie", en: "Myanmar" },
  { iso2: "BO", dialCode: "+591", fr: "Bolivie", en: "Bolivia" },
  {
    iso2: "BA",
    dialCode: "+387",
    fr: "Bosnie-Herzégovine",
    en: "Bosnia and Herzegovina",
  },
  { iso2: "BW", dialCode: "+267", fr: "Botswana", en: "Botswana" },
  { iso2: "BR", dialCode: "+55", fr: "Brésil", en: "Brazil" },
  { iso2: "BN", dialCode: "+673", fr: "Brunei", en: "Brunei" },
  { iso2: "BG", dialCode: "+359", fr: "Bulgarie", en: "Bulgaria" },
  {
    iso2: "BF",
    dialCode: "+226",
    fr: "Burkina Faso",
    en: "Burkina Faso",
  },
  { iso2: "BI", dialCode: "+257", fr: "Burundi", en: "Burundi" },
  { iso2: "KH", dialCode: "+855", fr: "Cambodge", en: "Cambodia" },
  { iso2: "CM", dialCode: "+237", fr: "Cameroun", en: "Cameroon" },
  { iso2: "CA", dialCode: "+1", fr: "Canada", en: "Canada" },
  { iso2: "CV", dialCode: "+238", fr: "Cap-Vert", en: "Cabo Verde" },
  {
    iso2: "CF",
    dialCode: "+236",
    fr: "République centrafricaine",
    en: "Central African Republic",
  },
  { iso2: "CL", dialCode: "+56", fr: "Chili", en: "Chile" },
  { iso2: "CN", dialCode: "+86", fr: "Chine", en: "China" },
  {
    iso2: "CY",
    dialCode: "+357",
    fr: "Chypre",
    en: "Cyprus",
  },
  { iso2: "CO", dialCode: "+57", fr: "Colombie", en: "Colombia" },
  { iso2: "KM", dialCode: "+269", fr: "Comores", en: "Comoros" },
  { iso2: "CG", dialCode: "+242", fr: "Congo", en: "Congo" },
  {
    iso2: "CD",
    dialCode: "+243",
    fr: "République démocratique du Congo",
    en: "DR Congo",
  },
  {
    iso2: "KP",
    dialCode: "+850",
    fr: "Corée du Nord",
    en: "North Korea",
  },
  {
    iso2: "KR",
    dialCode: "+82",
    fr: "Corée du Sud",
    en: "South Korea",
  },
  { iso2: "CR", dialCode: "+506", fr: "Costa Rica", en: "Costa Rica" },
  {
    iso2: "CI",
    dialCode: "+225",
    fr: "Côte d'Ivoire",
    en: "Côte d'Ivoire",
  },
  { iso2: "HR", dialCode: "+385", fr: "Croatie", en: "Croatia" },
  { iso2: "CU", dialCode: "+53", fr: "Cuba", en: "Cuba" },
  { iso2: "CW", dialCode: "+599", fr: "Curaçao", en: "Curaçao" },
  { iso2: "DK", dialCode: "+45", fr: "Danemark", en: "Denmark" },
  { iso2: "DJ", dialCode: "+253", fr: "Djibouti", en: "Djibouti" },
  { iso2: "DM", dialCode: "+1767", fr: "Dominique", en: "Dominica" },
  { iso2: "EG", dialCode: "+20", fr: "Égypte", en: "Egypt" },
  {
    iso2: "AE",
    dialCode: "+971",
    fr: "Émirats arabes unis",
    en: "United Arab Emirates",
  },
  { iso2: "EC", dialCode: "+593", fr: "Équateur", en: "Ecuador" },
  {
    iso2: "ER",
    dialCode: "+291",
    fr: "Érythrée",
    en: "Eritrea",
  },
  { iso2: "ES", dialCode: "+34", fr: "Espagne", en: "Spain" },
  { iso2: "EE", dialCode: "+372", fr: "Estonie", en: "Estonia" },
  {
    iso2: "SZ",
    dialCode: "+268",
    fr: "Eswatini",
    en: "Eswatini",
  },
  {
    iso2: "US",
    dialCode: "+1",
    fr: "États-Unis",
    en: "United States",
  },
  { iso2: "ET", dialCode: "+251", fr: "Éthiopie", en: "Ethiopia" },
  { iso2: "FJ", dialCode: "+679", fr: "Fidji", en: "Fiji" },
  { iso2: "FI", dialCode: "+358", fr: "Finlande", en: "Finland" },
  { iso2: "FR", dialCode: "+33", fr: "France", en: "France" },
  { iso2: "GA", dialCode: "+241", fr: "Gabon", en: "Gabon" },
  { iso2: "GM", dialCode: "+220", fr: "Gambie", en: "Gambia" },
  { iso2: "GE", dialCode: "+995", fr: "Géorgie", en: "Georgia" },
  { iso2: "GH", dialCode: "+233", fr: "Ghana", en: "Ghana" },
  { iso2: "GI", dialCode: "+350", fr: "Gibraltar", en: "Gibraltar" },
  { iso2: "GR", dialCode: "+30", fr: "Grèce", en: "Greece" },
  { iso2: "GD", dialCode: "+1473", fr: "Grenade", en: "Grenada" },
  { iso2: "GL", dialCode: "+299", fr: "Groenland", en: "Greenland" },
  { iso2: "GP", dialCode: "+590", fr: "Guadeloupe", en: "Guadeloupe" },
  { iso2: "GU", dialCode: "+1671", fr: "Guam", en: "Guam" },
  { iso2: "GT", dialCode: "+502", fr: "Guatemala", en: "Guatemala" },
  { iso2: "GG", dialCode: "+44", fr: "Guernesey", en: "Guernsey" },
  { iso2: "GN", dialCode: "+224", fr: "Guinée", en: "Guinea" },
  {
    iso2: "GQ",
    dialCode: "+240",
    fr: "Guinée équatoriale",
    en: "Equatorial Guinea",
  },
  {
    iso2: "GW",
    dialCode: "+245",
    fr: "Guinée-Bissau",
    en: "Guinea-Bissau",
  },
  { iso2: "GY", dialCode: "+592", fr: "Guyana", en: "Guyana" },
  {
    iso2: "GF",
    dialCode: "+594",
    fr: "Guyane française",
    en: "French Guiana",
  },
  { iso2: "HT", dialCode: "+509", fr: "Haïti", en: "Haiti" },
  { iso2: "HN", dialCode: "+504", fr: "Honduras", en: "Honduras" },
  { iso2: "HK", dialCode: "+852", fr: "Hong Kong", en: "Hong Kong" },
  { iso2: "HU", dialCode: "+36", fr: "Hongrie", en: "Hungary" },
  {
    iso2: "IM",
    dialCode: "+44",
    fr: "Île de Man",
    en: "Isle of Man",
  },
  { iso2: "KY", dialCode: "+1345", fr: "Îles Caïmans", en: "Cayman Islands" },
  {
    iso2: "MH",
    dialCode: "+692",
    fr: "Îles Marshall",
    en: "Marshall Islands",
  },
  { iso2: "SB", dialCode: "+677", fr: "Îles Salomon", en: "Solomon Islands" },
  {
    iso2: "TC",
    dialCode: "+1649",
    fr: "Îles Turques-et-Caïques",
    en: "Turks and Caicos Islands",
  },
  {
    iso2: "VG",
    dialCode: "+1284",
    fr: "Îles Vierges britanniques",
    en: "British Virgin Islands",
  },
  {
    iso2: "VI",
    dialCode: "+1340",
    fr: "Îles Vierges des États-Unis",
    en: "U.S. Virgin Islands",
  },
  { iso2: "IN", dialCode: "+91", fr: "Inde", en: "India" },
  { iso2: "ID", dialCode: "+62", fr: "Indonésie", en: "Indonesia" },
  { iso2: "IQ", dialCode: "+964", fr: "Irak", en: "Iraq" },
  { iso2: "IR", dialCode: "+98", fr: "Iran", en: "Iran" },
  { iso2: "IE", dialCode: "+353", fr: "Irlande", en: "Ireland" },
  { iso2: "IS", dialCode: "+354", fr: "Islande", en: "Iceland" },
  { iso2: "IL", dialCode: "+972", fr: "Israël", en: "Israel" },
  { iso2: "IT", dialCode: "+39", fr: "Italie", en: "Italy" },
  { iso2: "JM", dialCode: "+1876", fr: "Jamaïque", en: "Jamaica" },
  { iso2: "JP", dialCode: "+81", fr: "Japon", en: "Japan" },
  { iso2: "JE", dialCode: "+44", fr: "Jersey", en: "Jersey" },
  { iso2: "JO", dialCode: "+962", fr: "Jordanie", en: "Jordan" },
  { iso2: "KZ", dialCode: "+7", fr: "Kazakhstan", en: "Kazakhstan" },
  { iso2: "KE", dialCode: "+254", fr: "Kenya", en: "Kenya" },
  { iso2: "KG", dialCode: "+996", fr: "Kirghizistan", en: "Kyrgyzstan" },
  { iso2: "KI", dialCode: "+686", fr: "Kiribati", en: "Kiribati" },
  { iso2: "XK", dialCode: "+383", fr: "Kosovo", en: "Kosovo" },
  { iso2: "KW", dialCode: "+965", fr: "Koweït", en: "Kuwait" },
  { iso2: "LA", dialCode: "+856", fr: "Laos", en: "Laos" },
  { iso2: "LS", dialCode: "+266", fr: "Lesotho", en: "Lesotho" },
  { iso2: "LV", dialCode: "+371", fr: "Lettonie", en: "Latvia" },
  { iso2: "LB", dialCode: "+961", fr: "Liban", en: "Lebanon" },
  { iso2: "LR", dialCode: "+231", fr: "Liberia", en: "Liberia" },
  { iso2: "LY", dialCode: "+218", fr: "Libye", en: "Libya" },
  {
    iso2: "LI",
    dialCode: "+423",
    fr: "Liechtenstein",
    en: "Liechtenstein",
  },
  { iso2: "LT", dialCode: "+370", fr: "Lituanie", en: "Lithuania" },
  { iso2: "LU", dialCode: "+352", fr: "Luxembourg", en: "Luxembourg" },
  { iso2: "MO", dialCode: "+853", fr: "Macao", en: "Macau" },
  {
    iso2: "MK",
    dialCode: "+389",
    fr: "Macédoine du Nord",
    en: "North Macedonia",
  },
  { iso2: "MG", dialCode: "+261", fr: "Madagascar", en: "Madagascar" },
  { iso2: "MY", dialCode: "+60", fr: "Malaisie", en: "Malaysia" },
  { iso2: "MW", dialCode: "+265", fr: "Malawi", en: "Malawi" },
  { iso2: "MV", dialCode: "+960", fr: "Maldives", en: "Maldives" },
  { iso2: "ML", dialCode: "+223", fr: "Mali", en: "Mali" },
  { iso2: "MT", dialCode: "+356", fr: "Malte", en: "Malta" },
  { iso2: "MA", dialCode: "+212", fr: "Maroc", en: "Morocco" },
  { iso2: "MQ", dialCode: "+596", fr: "Martinique", en: "Martinique" },
  { iso2: "MU", dialCode: "+230", fr: "Maurice", en: "Mauritius" },
  { iso2: "MR", dialCode: "+222", fr: "Mauritanie", en: "Mauritania" },
  { iso2: "YT", dialCode: "+262", fr: "Mayotte", en: "Mayotte" },
  { iso2: "MX", dialCode: "+52", fr: "Mexique", en: "Mexico" },
  { iso2: "FM", dialCode: "+691", fr: "Micronésie", en: "Micronesia" },
  { iso2: "MD", dialCode: "+373", fr: "Moldavie", en: "Moldova" },
  { iso2: "MC", dialCode: "+377", fr: "Monaco", en: "Monaco" },
  { iso2: "MN", dialCode: "+976", fr: "Mongolie", en: "Mongolia" },
  { iso2: "ME", dialCode: "+382", fr: "Monténégro", en: "Montenegro" },
  { iso2: "MS", dialCode: "+1664", fr: "Montserrat", en: "Montserrat" },
  { iso2: "MZ", dialCode: "+258", fr: "Mozambique", en: "Mozambique" },
  { iso2: "NA", dialCode: "+264", fr: "Namibie", en: "Namibia" },
  { iso2: "NR", dialCode: "+674", fr: "Nauru", en: "Nauru" },
  { iso2: "NP", dialCode: "+977", fr: "Népal", en: "Nepal" },
  {
    iso2: "NI",
    dialCode: "+505",
    fr: "Nicaragua",
    en: "Nicaragua",
  },
  { iso2: "NE", dialCode: "+227", fr: "Niger", en: "Niger" },
  { iso2: "NG", dialCode: "+234", fr: "Nigeria", en: "Nigeria" },
  { iso2: "NU", dialCode: "+683", fr: "Niue", en: "Niue" },
  { iso2: "NO", dialCode: "+47", fr: "Norvège", en: "Norway" },
  {
    iso2: "NC",
    dialCode: "+687",
    fr: "Nouvelle-Calédonie",
    en: "New Caledonia",
  },
  {
    iso2: "NZ",
    dialCode: "+64",
    fr: "Nouvelle-Zélande",
    en: "New Zealand",
  },
  { iso2: "OM", dialCode: "+968", fr: "Oman", en: "Oman" },
  { iso2: "UG", dialCode: "+256", fr: "Ouganda", en: "Uganda" },
  { iso2: "UZ", dialCode: "+998", fr: "Ouzbékistan", en: "Uzbekistan" },
  { iso2: "PK", dialCode: "+92", fr: "Pakistan", en: "Pakistan" },
  { iso2: "PW", dialCode: "+680", fr: "Palaos", en: "Palau" },
  { iso2: "PS", dialCode: "+970", fr: "Palestine", en: "Palestine" },
  { iso2: "PA", dialCode: "+507", fr: "Panama", en: "Panama" },
  {
    iso2: "PG",
    dialCode: "+675",
    fr: "Papouasie-Nouvelle-Guinée",
    en: "Papua New Guinea",
  },
  { iso2: "PY", dialCode: "+595", fr: "Paraguay", en: "Paraguay" },
  { iso2: "NL", dialCode: "+31", fr: "Pays-Bas", en: "Netherlands" },
  { iso2: "PE", dialCode: "+51", fr: "Pérou", en: "Peru" },
  { iso2: "PH", dialCode: "+63", fr: "Philippines", en: "Philippines" },
  { iso2: "PL", dialCode: "+48", fr: "Pologne", en: "Poland" },
  {
    iso2: "PF",
    dialCode: "+689",
    fr: "Polynésie française",
    en: "French Polynesia",
  },
  { iso2: "PR", dialCode: "+1787", fr: "Porto Rico", en: "Puerto Rico" },
  { iso2: "PT", dialCode: "+351", fr: "Portugal", en: "Portugal" },
  { iso2: "QA", dialCode: "+974", fr: "Qatar", en: "Qatar" },
  {
    iso2: "CZ",
    dialCode: "+420",
    fr: "République tchèque",
    en: "Czechia",
  },
  {
    iso2: "DO",
    dialCode: "+1809",
    fr: "République dominicaine",
    en: "Dominican Republic",
  },
  { iso2: "RE", dialCode: "+262", fr: "Réunion", en: "Réunion" },
  { iso2: "RO", dialCode: "+40", fr: "Roumanie", en: "Romania" },
  { iso2: "GB", dialCode: "+44", fr: "Royaume-Uni", en: "United Kingdom" },
  { iso2: "RU", dialCode: "+7", fr: "Russie", en: "Russia" },
  { iso2: "RW", dialCode: "+250", fr: "Rwanda", en: "Rwanda" },
  {
    iso2: "EH",
    dialCode: "+212",
    fr: "Sahara occidental",
    en: "Western Sahara",
  },
  {
    iso2: "BL",
    dialCode: "+590",
    fr: "Saint-Barthélemy",
    en: "Saint Barthélemy",
  },
  {
    iso2: "KN",
    dialCode: "+1869",
    fr: "Saint-Christophe-et-Niévès",
    en: "Saint Kitts and Nevis",
  },
  { iso2: "SM", dialCode: "+378", fr: "Saint-Marin", en: "San Marino" },
  {
    iso2: "MF",
    dialCode: "+590",
    fr: "Saint-Martin",
    en: "Saint Martin",
  },
  {
    iso2: "PM",
    dialCode: "+508",
    fr: "Saint-Pierre-et-Miquelon",
    en: "Saint Pierre and Miquelon",
  },
  {
    iso2: "VC",
    dialCode: "+1784",
    fr: "Saint-Vincent-et-les-Grenadines",
    en: "Saint Vincent and the Grenadines",
  },
  { iso2: "SH", dialCode: "+290", fr: "Sainte-Hélène", en: "Saint Helena" },
  { iso2: "LC", dialCode: "+1758", fr: "Sainte-Lucie", en: "Saint Lucia" },
  { iso2: "SV", dialCode: "+503", fr: "Salvador", en: "El Salvador" },
  { iso2: "WS", dialCode: "+685", fr: "Samoa", en: "Samoa" },
  {
    iso2: "ST",
    dialCode: "+239",
    fr: "Sao Tomé-et-Principe",
    en: "Sao Tome and Principe",
  },
  { iso2: "SN", dialCode: "+221", fr: "Sénégal", en: "Senegal" },
  { iso2: "RS", dialCode: "+381", fr: "Serbie", en: "Serbia" },
  { iso2: "SC", dialCode: "+248", fr: "Seychelles", en: "Seychelles" },
  {
    iso2: "SL",
    dialCode: "+232",
    fr: "Sierra Leone",
    en: "Sierra Leone",
  },
  { iso2: "SG", dialCode: "+65", fr: "Singapour", en: "Singapore" },
  { iso2: "SK", dialCode: "+421", fr: "Slovaquie", en: "Slovakia" },
  { iso2: "SI", dialCode: "+386", fr: "Slovénie", en: "Slovenia" },
  { iso2: "SO", dialCode: "+252", fr: "Somalie", en: "Somalia" },
  { iso2: "SD", dialCode: "+249", fr: "Soudan", en: "Sudan" },
  { iso2: "SS", dialCode: "+211", fr: "Soudan du Sud", en: "South Sudan" },
  { iso2: "LK", dialCode: "+94", fr: "Sri Lanka", en: "Sri Lanka" },
  { iso2: "SE", dialCode: "+46", fr: "Suède", en: "Sweden" },
  { iso2: "CH", dialCode: "+41", fr: "Suisse", en: "Switzerland" },
  { iso2: "SR", dialCode: "+597", fr: "Suriname", en: "Suriname" },
  { iso2: "SY", dialCode: "+963", fr: "Syrie", en: "Syria" },
  { iso2: "TJ", dialCode: "+992", fr: "Tadjikistan", en: "Tajikistan" },
  { iso2: "TW", dialCode: "+886", fr: "Taïwan", en: "Taiwan" },
  { iso2: "TZ", dialCode: "+255", fr: "Tanzanie", en: "Tanzania" },
  { iso2: "TD", dialCode: "+235", fr: "Tchad", en: "Chad" },
  { iso2: "TH", dialCode: "+66", fr: "Thaïlande", en: "Thailand" },
  {
    iso2: "TL",
    dialCode: "+670",
    fr: "Timor oriental",
    en: "Timor-Leste",
  },
  { iso2: "TG", dialCode: "+228", fr: "Togo", en: "Togo" },
  { iso2: "TO", dialCode: "+676", fr: "Tonga", en: "Tonga" },
  {
    iso2: "TT",
    dialCode: "+1868",
    fr: "Trinité-et-Tobago",
    en: "Trinidad and Tobago",
  },
  { iso2: "TN", dialCode: "+216", fr: "Tunisie", en: "Tunisia" },
  { iso2: "TM", dialCode: "+993", fr: "Turkménistan", en: "Turkmenistan" },
  { iso2: "TR", dialCode: "+90", fr: "Turquie", en: "Turkey" },
  { iso2: "TV", dialCode: "+688", fr: "Tuvalu", en: "Tuvalu" },
  { iso2: "UA", dialCode: "+380", fr: "Ukraine", en: "Ukraine" },
  { iso2: "UY", dialCode: "+598", fr: "Uruguay", en: "Uruguay" },
  { iso2: "VU", dialCode: "+678", fr: "Vanuatu", en: "Vanuatu" },
  { iso2: "VA", dialCode: "+379", fr: "Vatican", en: "Vatican City" },
  { iso2: "VE", dialCode: "+58", fr: "Venezuela", en: "Venezuela" },
  { iso2: "VN", dialCode: "+84", fr: "Vietnam", en: "Vietnam" },
  {
    iso2: "WF",
    dialCode: "+681",
    fr: "Wallis-et-Futuna",
    en: "Wallis and Futuna",
  },
  { iso2: "YE", dialCode: "+967", fr: "Yémen", en: "Yemen" },
  { iso2: "ZM", dialCode: "+260", fr: "Zambie", en: "Zambia" },
  { iso2: "ZW", dialCode: "+263", fr: "Zimbabwe", en: "Zimbabwe" },
];

export const DEFAULT_COUNTRY_CODE = COUNTRY_CODES.find(
  (c) => c.iso2 === DEFAULT_COUNTRY_ISO2,
)!;

/** ISO 3166-1 alpha-2 → flag emoji, via the Unicode regional-indicator
 * trick (each letter maps to 0x1F1E6 + its offset from "A"). Kept short in
 * the select's closed box — the flag plus dial code, not the spelled-out
 * name — so the row fits on one line whatever country is selected. */
export function flagEmoji(iso2: string): string {
  return String.fromCodePoint(
    ...[...iso2.toUpperCase()].map(
      (char) => 0x1f1e6 + (char.charCodeAt(0) - 65),
    ),
  );
}

/** All entries except the default, sorted by localized name — used to fill
 * the dropdown below the pinned default option. */
export function otherCountryCodes(lang: Locale): CountryCode[] {
  return COUNTRY_CODES.filter((c) => c.iso2 !== DEFAULT_COUNTRY_ISO2).sort(
    (a, b) => a[lang].localeCompare(b[lang], lang),
  );
}
